baseURL = "http://example.org/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "Avram R.P. Rago"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

[params]
  # LoveIt theme version
  version = "0.2.X"

[menu]
  [[menu.main]]
    identifier = "Research"
    pre = ""
    post = ""
    name = "Research"
    url = "/Research/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "Watches"
    pre = ""
    post = ""
    name = "Watches"
    url = "/Watches/"
    title = ""
    weight = 3
    
  [[menu.main]]
    identifier = "Cooking"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Cooking"
    url = "/Cooking/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
